### ISSUE TITLE
Resource mode not resolvable for Bibcode

### ISSUE THREAD

**Issue by asajedi** [FC4E-WP5/fc4eosc-PIDMR-api#100]
Resource mode is activated for Bibcode however is not resolvable. Please check the following Bibcode identifier:  

https://api.pidmr.devel.argo.grnet.gr/v1/metaresolvers/resolve?pidMode=resource&redirect=true&pid=2022icrc.confE1145C

**Comment by fbasios** [comment]
Good morning, Ali. Can you try again? The issue has been fixed.
