### ISSUE TITLE
& in Bibcode RegEx can not be validated

### ISSUE THREAD

**Issue by asajedi** [FC4E-WP5/fc4eosc-PIDMR-api#101]
Given the following Bibcode Identifier

2024A&A...688A...6A

and the following RexEx pattern

^\d{4}[A-Za-z&\.]{5}[A-Za-z0-9\.]{4}[A-Za-z0-9\.][A-Za-z0-9\.]{4}[A-Za-z]$

the & character can not be validated.

Please check and report as soon as possible.

**Comment by fbasios** [comment]
There is an issue with the ampersand character. The backend interprets it as a URL parameter. The frontend needs to encode it as %26, and the backend should decode it back to &. We will fix it shortly.

**Comment by fbasios** [comment]
This issue has been fixed.

**Comment by asajedi** [comment]
Great, thank you very much.
