### ISSUE TITLE
Unproper error message if an identifier can not be resolved by PIDMR backend  (invalid identifier)

### ISSUE THREAD

**Issue by asajedi** [FC4E-WP5/fc4eosc-PIDMR-api#102]
code	500
message	"Cannot communicate with metaresolver: Hostname pidmr.lab.pidconsortium.net not verified:\n    certificate: sha256/JNruRqJ6ITdwwfmhj8ekBCnypweKca6yU7CMTb1DMrY=\n    DN: CN=prefix-info.pid.gwdg.de, O=Gesellschaft für wissenschaftliche Datenverarbeitung mbH, ST=Niedersachsen, C=DE\n    subjectAltNames: [prefix-info.pid.gwdg.de]"

**Comment by fbasios** [comment]
There was a test Provider in the backend where its regex matched the 2022icrc.confE1145C. Consequently, when resolving 2022icrc.confE1145C, the backend considered it belonged to the test Provider. This test Provider had metadata mode, so the backend requested metadata from the Handle system for 2022icrc.confE1145C. Hence, the specific message.
