### ISSUE TITLE
Illegal character in path at index 22

### ISSUE THREAD

**Issue by asajedi** [FC4E-WP5/fc4eosc-PIDMR-api#104]
The following request:

https://api.pidmr.devel.argo.grnet.gr/v1/metaresolvers/resolve?pidMode=landingpage&redirect=true&pid=https://raid.org/10.82841/054fded3

oututs the following response

{"code":500,"message":"Illegal character in path at index 22: https://raid.org//%7Bx[1]%7D"}

could you please check.

**Comment by fbasios** [comment]
Hello Ali. Check again please. It works now.
