### ISSUE TITLE
Zbl PID identification problem

### ISSUE THREAD

**Issue by asajedi** [FC4E-WP5/fc4eosc-PIDMR-api#110]
There seems to be an issue with RegEx array. The Zbl PID could be of the forms:

1509.68329
7800005
07800005

Currently there are 2 RegEx pattern in the DB, namely:
^(\d+\.\d+)$ für identifying 1509.68329 
and
^(0?\d{4,7})$ for identifying 07800005 and 07800005

The UI identify 1509.68329 correctly but not 7800005 and 07800005

Could you please check

**Comment by fbasios** [comment]
Hi Ali. We have fixed the issue. Could you check, please?

**Comment by asajedi** [comment]
This is fixed. Thank you.
