### ISSUE TITLE
New Endpoint Testing any string for being a PID

### ISSUE THREAD

**Issue by bingert** [FC4E-WP5/fc4eosc-PIDMR-api#29]
As discussed  with DataCite during the Den Haag meeting a possible integration of the PIDMR could be by providing an end-point in the PIDMR API that allows to test any string for being a PID.
The Endpoint should return the detected type (list) of the PID.
Should we add other information here?

**Comment by themiszamani** [comment]
Dear @bingert 

We should have a discussion with DataCite about this. 
Best
Themis

**Comment by bingert** [comment]
Testing:
https://apimr.devel.argo.grnet.gr/swagger-ui/#/Provider/get_v1_providers_identify

**Comment by themiszamani** [comment]
We updated the Incomplete with AMBIGIOUS .
We added also the type of resolutions we support.

**Comment by themiszamani** [comment]
@bingert is that ok?

**Comment by themiszamani** [comment]
@bingert any news?

**Comment by bingert** [comment]
Yes fine, I'll close the issue
