### ISSUE TITLE
strange error (error 500) when inserting pid with a leading or trailing space

### ISSUE THREAD

**Issue by asajedi** [FC4E-WP5/fc4eosc-PIDMR-api#48]
This error is reported on https://wiki.eduuni.fi/pages/viewpage.action?pageId=450081765 by Serafeim Chatzopoulos (OpenAIRE),

e.g., https://api.pidmr.devel.argo.grnet.gr/v1/metaresolvers/resolve?pid=10.1038/scientificamerican0501-34%20&pidMode=metadata&redirect=true

**Comment by asajedi** [comment]
The solution would be to trim the pid before sending the request to pidmr backend as currently we have no means of triming in the backend.

**Comment by fbasios** [comment]
@asajedi We fixed this issue and deployed it on https://api.pidmr.argo.grnet.gr.
